# Health Index
### Code & Cry

1. Poverty 
2. Asthma 
3. Pollution Burden
4. Low Birth Weight
5. Cardiovascular Disease

[Insert reason why we're using indices]. We will be using the above five indicators and scoring them between 1 and 4. We will then sum the five indicators to define the overarching Health Index, which will have a total of 20 possible points. Higher scores ([**later find the quantiles of each fips code, and insert the top quantile for the scores**]) indicate higher health and environmental vulnerabilities, whereas lower scores ([**same as higher scores**]) indicate lower vulnerabilities. 

In [1]:
import pandas as pd
import geopandas as gpd
import plotly.express as px

In [2]:
#pull in dataset 
health = pd.read_csv('data/sf_health.csv')

In [3]:
#confirm that data was imported correctly
health.head()

FIPS  Total_Population      ZIP   Longitude   Latitude  \
0  6.075023e+09            3972.0  94124.0 -122.386139  37.727755   
1  6.075018e+09            3008.0  94130.0 -122.419701  37.861948   
2  6.075023e+09            2890.0  94124.0 -122.375965  37.735632   
3  6.075023e+09            5398.0  94124.0 -122.401760  37.735192   
4  6.075023e+09            3661.0  94124.0 -122.390088  37.721593   

   Pollution_Burden  Pollution_Burden_Pctl  Asthma  Asthma_Pctl  \
0             58.23                  88.31  123.98        96.44   
1             58.31                  88.51  106.14        94.28   
2             54.77                  81.89  123.98        96.44   
3             54.39                  81.12  123.98        96.44   
4             54.06                  80.44  123.98        96.44   

   Low_Birth_Weight  Low_Birth_Weight_Pctl  Cardiovascular_Disease  \
0              8.09                  96.82                   11.96   
1              8.59                  98.20                    7.42   
2              7.74                  95.32                   11.96   
3              6.41                  82.28                   11.96   
4              6.29                  80.16                   11.96   

   Cardiovascular_Disease_Pctl  Poverty  Poverty_Pctl  
0                        45.80     27.3         49.12  
1                         9.73     66.7         95.90  
2                        45.80     71.7         97.95  
3                        45.80     30.7         54.95  
4                        45.80     40.1         69.35

In [4]:
health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1040735 entries, 0 to 1040734
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   FIPS                         195 non-null    float64
 1   Total_Population             195 non-null    float64
 2   ZIP                          195 non-null    float64
 3   Longitude                    195 non-null    float64
 4   Latitude                     195 non-null    float64
 5   Pollution_Burden             195 non-null    float64
 6   Pollution_Burden_Pctl        195 non-null    float64
 7   Asthma                       195 non-null    float64
 8   Asthma_Pctl                  195 non-null    float64
 9   Low_Birth_Weight             191 non-null    float64
 10  Low_Birth_Weight_Pctl        191 non-null    float64
 11  Cardiovascular_Disease       195 non-null    float64
 12  Cardiovascular_Disease_Pctl  195 non-null    float64
 13  Poverty     

In [5]:
#FIPS code is currently a float and needs to be changed into a string for merging later on
health = pd.read_csv(
    'data/sf_health.csv',
    dtype=
    {
        'FIPS':str
    }
)
health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1040735 entries, 0 to 1040734
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   FIPS                         195 non-null    object 
 1   Total_Population             195 non-null    float64
 2   ZIP                          195 non-null    float64
 3   Longitude                    195 non-null    float64
 4   Latitude                     195 non-null    float64
 5   Pollution_Burden             195 non-null    float64
 6   Pollution_Burden_Pctl        195 non-null    float64
 7   Asthma                       195 non-null    float64
 8   Asthma_Pctl                  195 non-null    float64
 9   Low_Birth_Weight             191 non-null    float64
 10  Low_Birth_Weight_Pctl        191 non-null    float64
 11  Cardiovascular_Disease       195 non-null    float64
 12  Cardiovascular_Disease_Pctl  195 non-null    float64
 13  Poverty     

In [6]:
#FIPS code needs the leading 0 to merge with shapefile 
health['FIPS'] = health['FIPS'].str.replace('6075', '06075')
health.head()

FIPS  Total_Population      ZIP   Longitude   Latitude  \
0  06075023200            3972.0  94124.0 -122.386139  37.727755   
1  06075017902            3008.0  94130.0 -122.419701  37.861948   
2  06075023103            2890.0  94124.0 -122.375965  37.735632   
3  06075023001            5398.0  94124.0 -122.401760  37.735192   
4  06075023400            3661.0  94124.0 -122.390088  37.721593   

   Pollution_Burden  Pollution_Burden_Pctl  Asthma  Asthma_Pctl  \
0             58.23                  88.31  123.98        96.44   
1             58.31                  88.51  106.14        94.28   
2             54.77                  81.89  123.98        96.44   
3             54.39                  81.12  123.98        96.44   
4             54.06                  80.44  123.98        96.44   

   Low_Birth_Weight  Low_Birth_Weight_Pctl  Cardiovascular_Disease  \
0              8.09                  96.82                   11.96   
1              8.59                  98.20                    7.42   
2              7.74                  95.32                   11.96   
3              6.41                  82.28                   11.96   
4              6.29                  80.16                   11.96   

   Cardiovascular_Disease_Pctl  Poverty  Poverty_Pctl  
0                        45.80     27.3         49.12  
1                         9.73     66.7         95.90  
2                        45.80     71.7         97.95  
3                        45.80     30.7         54.95  
4                        45.80     40.1         69.35

## 1. Poverty
[insert description]

In [13]:
#define columns to keep for poverty index
columns_to_keep=['FIPS',
                 'Poverty',
                 'Poverty_Pctl',]

In [14]:
#add it to the poverty dataframe
poverty=health[columns_to_keep]
poverty.head()

FIPS  Poverty  Poverty_Pctl
0  06075023200     27.3         49.12
1  06075017902     66.7         95.90
2  06075023103     71.7         97.95
3  06075023001     30.7         54.95
4  06075023400     40.1         69.35

In [18]:
#identify quantiles for index
poverty.Poverty.describe()

count    193.000000
mean      21.955959
std       13.993673
min        3.300000
25%       12.500000
50%       18.000000
75%       27.300000
max       71.700000
Name: Poverty, dtype: float64

### Defining Quantiles 
• **Quantile 1** = census tract with poverty values less than 12.5

• **Quantile 2** = census tract with poverty values between 12.5 and 18.0

• **Quantile 3** = census tract with poverty values between 18.0 and 27.3

• **Quantile 4** = census tract with poverty values above 27.3

Q1 has the least rates of poverty, whereas Q4 has the highest rates of poverty. 

In [21]:
#query the census tracts in the fourth quantile only 
poverty[poverty.Poverty>27.3].count()

FIPS            48
Poverty         48
Poverty_Pctl    48
dtype: int64

In [31]:
# now that we confirmed that there are 48 census tracts with a score of 4 in the Poverty Index, let's define the all the census tracts within their respective scores
poverty_1=poverty[poverty.Poverty<12.5]
poverty_2=poverty[poverty['Poverty'].between(12.5, 18.0)]
poverty_3=poverty[poverty['Poverty'].between(18.0, 27.3)]
poverty_4=poverty[poverty.Poverty>27.3]

In [32]:
### Plot
